create table movie (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(50), genre VARCHAR(50), cover VARCHAR(50));
insert into movie (id, title, genre, cover) values (1, 'One Piece Film: Strong World', 'Action|Adventure|Animation|Comedy|Fantasy', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (2, 'My Fair Lady', 'Comedy|Drama|Musical|Romance', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (3, 'No Distance Left to Run', 'Documentary', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (4, 'Safety Last!', 'Action|Comedy|Romance', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (5, 'New Waterford Girl', 'Comedy', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (6, 'Black Balloon, The', 'Drama', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (7, 'The Beaver Trilogy', 'Comedy|Documentary|Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (8, 'Argentina latente', 'Documentary', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (9, 'Sunless (Sans Soleil)', 'Documentary', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (10, 'Deadly Trackers, The', 'Drama|Western', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (11, 'Parent Trap, The', 'Children|Comedy|Romance', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (12, 'General''s Daughter, The', 'Crime|Drama|Mystery|Thriller', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (13, 'Legion', 'Action|Fantasy|Horror|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (14, 'Weekend It Lives, The (Ax ''Em)', 'Horror', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (15, 'Women Robbers (Diebinnen)', 'Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (16, 'Flicka', 'Children|Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (17, 'Fantastic Four: Rise of the Silver Surfer', 'Action|Adventure|Sci-Fi', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (18, 'Sterile Cuckoo, The', 'Comedy|Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (19, 'Without a Paddle: Nature''s Calling', 'Adventure|Comedy', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (20, 'Blade: Trinity', 'Action|Fantasy|Horror|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (21, 'Something Ventured', 'Documentary', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (22, 'Down in the Delta', 'Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (23, 'Nanking', 'Documentary|War', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (24, 'Paperman', 'Animation|Comedy|Romance', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (25, 'Combien Tu M''aimes? (How Much Do You Love Me?)', 'Comedy|Romance', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (26, 'Chinese Odyssey 2002 (Tian xia wu shuang)', 'Action|Comedy|Romance', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (27, 'Conspirator, The', 'Drama', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (28, 'My Big Fat Greek Wedding', 'Comedy|Romance', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (29, 'My Perestroika', 'Documentary', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (30, 'Descendant of the Sun (Ri jie)', 'Action|Adventure|Fantasy|Sci-Fi', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (31, 'Fierce Creatures', 'Comedy', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (32, 'Dr. Crippen', 'Crime|Drama', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (33, 'Skellig', 'Drama|Fantasy|Mystery', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (34, 'Caprice', 'Comedy|Crime|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (35, 'Lady Death', 'Action|Animation|Horror', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (36, 'Universal Soldier: Day of Reckoning', 'Action|Sci-Fi|Thriller', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (37, 'Suspect Zero', 'Crime|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (38, 'Mysterious Geographic Explorations of Jasper Morello, The', 'Adventure|Animation', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (39, 'Manta, Manta', 'Comedy', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (40, 'Tokyo!', 'Drama', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (41, 'Amorosa', 'Drama', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (42, 'Operation Ganymed', 'Sci-Fi', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (43, 'Vision Quest', 'Drama|Romance', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (44, 'Moonlight Serenade', 'Drama', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (45, 'Lovelace', 'Drama', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (46, 'One Million Years B.C.', 'Adventure|Fantasy', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (47, 'Avenger ', 'Thriller', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (48, 'Family United (La gran familia española)', 'Comedy', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (49, 'Wonder Woman', 'Action|Adventure|Animation|Fantasy', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (50, 'Burning, The', 'Horror', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (51, 'Can''t Hardly Wait', 'Comedy|Drama|Romance', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (52, 'Crimson Rivers, The (Rivières pourpres, Les)', 'Crime|Drama|Mystery|Thriller', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (53, 'Andre', 'Adventure|Children|Drama', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (54, 'Me, Myself and Mum (Les garçons et Guillaume, à table!)', 'Comedy', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (55, 'Loose Cannons', 'Action|Comedy', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (56, 'Summer Days With Coo', 'Animation', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (57, 'Damsel in Distress, A', 'Comedy|Musical|Romance', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (58, 'Shrek the Musical', 'Children|Comedy|Fantasy|Musical', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (59, 'Following', 'Crime|Mystery|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (60, 'Survive Style 5+', 'Fantasy|Mystery|Romance|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (61, '33 Scenes from Life (33 sceny z zycia)', 'Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (62, 'Singin'' in the Rain', 'Comedy|Musical|Romance', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (63, 'Doctor Zhivago', 'Drama|Romance|War', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (64, 'Lethal Weapon 4', 'Action|Comedy|Crime|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (65, 'Brest Fortress (Brestskaya krepost)', 'Action|Drama|War', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (66, '20,000 Leagues Under the Sea', 'Adventure|Romance|Sci-Fi', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (67, 'Jasminum', 'Comedy|Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (68, 'These Are the Damned (a.k.a. The Damned)', 'Drama|Fantasy|Romance|Sci-Fi', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (69, 'Rebecca', 'Drama|Mystery|Romance|Thriller', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (70, 'Day the Earth Stood Still, The', 'Drama|Sci-Fi|Thriller|IMAX', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (71, 'Good Mother, The', 'Drama', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (72, 'Passion of the Christ, The', 'Drama', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (73, 'Zombie Island Massacre', 'Horror', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (74, 'The .44 Specialist', 'Action', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (75, 'Let''s Get Harry', 'Action|Adventure', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (76, 'Hunt, The (Caza, La)', 'Drama|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (77, 'Rembrandt', 'Drama', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (78, 'Crazy Mama', 'Action|Comedy', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (79, 'Doctor Who', 'Adventure|Sci-Fi', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (80, 'X from Outer Space, The (Uchû daikaijû Girara)', 'Horror|Sci-Fi', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (81, 'Girl Crazy', 'Comedy|Musical|Romance', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (82, 'Legends of the Canyon', 'Documentary', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (83, 'Antonio das Mortes (O Dragão da Maldade contra o Santo Guerreiro)', 'Drama|Western', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (84, 'Bikini Spring Break (Revenge of the Nerds'' Bikini Spring Break)', 'Comedy', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (85, 'Sweet and Lowdown', 'Comedy|Drama', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (86, 'Uncounted: The New Math of American Elections', 'Documentary', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (87, 'Red Hill', 'Crime|Thriller|Western', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (88, 'Texas Terror', 'Action|Romance|Western', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (89, 'Lions For Lambs', 'Drama|Thriller|War', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (90, 'In a Lonely Place', 'Drama|Film-Noir|Mystery|Romance', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (91, 'Dead Man', 'Drama|Mystery|Western', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (92, 'Prison (Fängelse) ', 'Drama', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (93, 'Young Black Stallion, The', 'Adventure|Children|Drama', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (94, 'Valiant', 'Adventure|Animation|Children|Comedy|Fantasy|War', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (95, 'Hamiltons, The', 'Drama|Horror|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');
insert into movie (id, title, genre, cover) values (96, 'Daylight', 'Horror|Thriller', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (97, 'Arthur and the Revenge of Maltazard (Arthur et la vengeance de Maltazard)', 'Animation|Children|Fantasy', 'http://dummyimage.com/500x700.png/dddddd/000000');
insert into movie (id, title, genre, cover) values (98, 'The Dark Matter of Love', 'Documentary', 'http://dummyimage.com/500x700.png/cc0000/ffffff');
insert into movie (id, title, genre, cover) values (99, 'Stuck in Love', 'Comedy|Drama|Romance', 'http://dummyimage.com/500x700.png/ff4444/ffffff');
insert into movie (id, title, genre, cover) values (100, 'The Damned', 'Horror|Mystery|Thriller', 'http://dummyimage.com/500x700.png/5fa2dd/ffffff');